use_frameworks!
# source 'https://cdn.cocoapods.org/'
# source 'https://github.com/smileidentity/smileid-ios'

platform :ios, '13.0'

target 'SmileID_Example' do
  pod 'SmileID', :path => '../'
  # pod 'SmileID'


  target 'SmileID_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["DEVELOPMENT_TEAM"] = "99P7YGX9Q6"
         end
    end
  end
end
