version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
  - package-ecosystem: "cocoapods"
    directory: "/" 
    schedule:
      interval: "weekly"
      day: monday
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
  - package-ecosystem: "cocoapods"
    directory: "/Example"
    schedule:
      interval: "weekly"
      day: monday
