version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: "swift"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      day: monday
    groups:
      swift-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: "github.com/airbnb/lottie-spm"
      - dependency-name: "github.com/fingerprintjs/fingerprintjs-ios"
      - dependency-name: "github.com/getsentry/sentry-cocoa"
  - package-ecosystem: "bundler"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
      day: monday
    groups:
      bundler-dependencies:
        patterns:
          - '*'
