version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    groups:
      swift-dependencies:
        patterns:
          - '*'
          
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    groups:
      bundler-dependencies:
        patterns:
          - '*'

