name: Setup
description: Setup the Smile ID CI Environment
inputs:
  xcode:
    description: The version of Xcode to select
  install-mint:
    description: Whether to install mint
    default: true
runs:
  using: composite
  steps:
  - name: Select Xcode ${{ inputs.xcode }}
    if: ${{ inputs.xcode }}
    shell: bash
    run: |
      set -euo pipefail
      XCODE_APP="/Applications/Xcode_${{ inputs.xcode }}.app"
      if [ -d "$XCODE_APP" ]; then
        echo "Switching to $XCODE_APP"
        sudo xcode-select --switch "$XCODE_APP"
      else
        echo "Requested $XCODE_APP not found; keeping default Xcode."
        echo "Available Xcodes:"
        ls -1 /Applications | grep -E '^Xcode' || true
        echo "Active Xcode: $(xcode-select -p)"
        xcodebuild -version || true
      fi

  - name: Install Mint via Homebrew
    run: brew install mint
    if: ${{ inputs.install-mint == 'true' }}
    shell: bash

  - name: Install Ruby Gems
    run: bundle install
    shell: bash
