{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate\/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@SmileID@objc(cs)URLDelegate(im)URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","title":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"urlSession","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"task","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionTask","kind":"typeIdentifier","text":"URLSessionTask"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSendBodyData"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"text":", ","kind":"text"},{"text":"totalBytesSent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalBytesExpectedToSend"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","kind":"identifier"}],"modules":[{"name":"SmileID"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"URLSessionTaskDelegate.urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"task","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLSessionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":", "},{"text":"didSendBodyData","kind":"externalParam"},{"kind":"text","text":" "},{"text":"bytesSent","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalBytesSent"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"totalBytesExpectedToSend","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smileid\/urldelegate\/urlsession(_:task:didsendbodydata:totalbytessent:totalbytesexpectedtosend:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smileid\/urldelegate\/urlsession(_:task:didsendbodydata:totalbytessent:totalbytesexpectedtosend:)"]}],"references":{"doc://org.cocoapods.SmileID/documentation/SmileID/URLDelegate/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)":{"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate\/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLSessionTask","text":"URLSessionTask","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didSendBodyData","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"totalBytesSent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"totalBytesExpectedToSend"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","kind":"identifier"}],"url":"\/documentation\/smileid\/urldelegate\/urlsession(_:task:didsendbodydata:totalbytessent:totalbytesexpectedtosend:)","title":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)"},"doc://org.cocoapods.SmileID/documentation/SmileID":{"url":"\/documentation\/smileid","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID","title":"SmileID","type":"topic","abstract":[],"role":"collection"},"doc://org.cocoapods.SmileID/documentation/SmileID/URLDelegate":{"url":"\/documentation\/smileid\/urldelegate","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"URLDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate","navigatorTitle":[{"text":"URLDelegate","kind":"identifier"}],"title":"URLDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"URLSession:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier","text":"NSURLSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"task:"},{"text":"(","kind":"text"},{"text":"NSURLSessionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"task"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSendBodyData:"},{"text":"(","kind":"text"},{"text":"int64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"bytesSent"},{"kind":"text","text":" "},{"text":"totalBytesSent:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"totalBytesSent"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalBytesExpectedToSend:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":") "},{"text":"totalBytesExpectedToSend","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","path":"\/references\/doc:~1~1org.cocoapods.SmileID~1documentation~1SmileID~1URLDelegate~1urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:"}],"path":"\/references\/doc:~1~1org.cocoapods.SmileID~1documentation~1SmileID~1URLDelegate~1urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SmileID~1documentation~1SmileID~1URLDelegate\/title","value":"URLDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SmileID~1documentation~1SmileID~1URLDelegate\/fragments","value":[{"text":"URLDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}