{"hierarchy":{"paths":[[]]},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Framework","role":"collection","externalID":"SmileID","title":"SmileID","symbolKind":"module","modules":[{"name":"SmileID"}]},"variants":[{"paths":["\/documentation\/smileid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smileid"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BiometricKycJobResult","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DefaultServiceHeaderProvider","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DocumentVerificationJobResult","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedDocumentVerificationJobResult","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/JobResult","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/JobStatusResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/LocalStorage","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SelfieViewModel","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmartSelfieJobResult","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileID","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDResourcesHelper","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDService","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLUploadSessionPublisherImplementation"]},{"identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BiometricKycResultDelegate","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DocumentVerificationResultDelegate","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedDocumentVerificationResultDelegate","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/FontType","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmartSelfieResultDelegate","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDServiceable","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIdTheme","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLUploadSessionPublisher"],"title":"Protocols"},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Actions","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ActivityIndicator","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Antifraud","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/AspectRatioRoundedRectangle","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/AuthenticationRequest","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/AuthenticationResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/AvailableIdType","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BankCode","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BvnTotpModeRequest","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BvnTotpModeResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BvnTotpRequest","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BvnTotpResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Config","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ConsentDeniedScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ConsentInfo","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ConsentScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Country","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/CountryInfo","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DocumentCaptureInstructionsScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DocumentCaptureScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedKycAsyncResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedKycRequest","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedKycResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EpilogueFont","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/HTTPHeader","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/HTTPQueryParameters","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/HostedWeb","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/IdInfo","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/IdSelection","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/IdType","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ImageCaptureConfirmationDialog","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ImageLinks","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/JobStatusRequest","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/OrchestratedConsentScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/OrchestratedSelfieCaptureScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/PartnerParams","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/PrepUploadRequest","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/PrepUploadResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProcessingErrorScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProcessingInProgressScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProcessingScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProductsConfigRequest","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProductsConfigResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/RadioGroupSelector","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SearchableDropdownSelector","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SelfieCaptureScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ServicesResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmartSelfieInstructionsScreen","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileButton","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDErrorResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDLocalizableStrings","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SubmitBvnTotpRequest","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SubmitBvnTotpResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SuspectUser","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/UploadImageInfo","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/UploadRequest","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ValidDocument","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ValidDocumentsResponse"]},{"title":"Functions","identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/generateJobId()","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/generateUserId()"]},{"title":"Type Aliases","identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BiometricKycJobStatusResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BvnVerificationMode","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/CountryCodeToCountryInfo","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DocumentVerificationJobStatusResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedDocumentVerificationJobStatusResponse","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/IdTypeKeyToAvailableIdType","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/IdTypes","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmartSelfieJobStatusResponse"]},{"identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ActionResult","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ImageType","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/JobType","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProcessingState","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/RequiredField","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDError","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/UploadResponse"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Combine","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Foundation","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Swift","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SwiftUI"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.SmileID/documentation/SmileID/JobStatusRequest":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobStatusRequest"}],"role":"symbol","navigatorTitle":[{"text":"JobStatusRequest","kind":"identifier"}],"type":"topic","kind":"symbol","title":"JobStatusRequest","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/JobStatusRequest","url":"\/documentation\/smileid\/jobstatusrequest","abstract":[]},"doc://org.cocoapods.SmileID/documentation/SmileID/OrchestratedSelfieCaptureScreen":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/OrchestratedSelfieCaptureScreen","abstract":[{"type":"text","text":"Orchestrates the selfie capture flow - navigates between instructions, requesting permissions,"},{"text":" ","type":"text"},{"text":"showing camera view, and displaying processing screen","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/smileid\/orchestratedselfiecapturescreen","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OrchestratedSelfieCaptureScreen","kind":"identifier"}],"title":"OrchestratedSelfieCaptureScreen","navigatorTitle":[{"text":"OrchestratedSelfieCaptureScreen","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/JobStatusResponse":{"type":"topic","title":"JobStatusResponse","role":"symbol","url":"\/documentation\/smileid\/jobstatusresponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JobStatusResponse"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/JobStatusResponse","abstract":[],"navigatorTitle":[{"text":"JobStatusResponse","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileIDServiceable":{"url":"\/documentation\/smileid\/smileidserviceable","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SmileIDServiceable"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDServiceable","navigatorTitle":[{"text":"SmileIDServiceable","kind":"identifier"}],"title":"SmileIDServiceable"},"doc://org.cocoapods.SmileID/documentation/SmileID/EnhancedKycResponse":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedKycResponse","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnhancedKycResponse"}],"role":"symbol","title":"EnhancedKycResponse","navigatorTitle":[{"kind":"identifier","text":"EnhancedKycResponse"}],"url":"\/documentation\/smileid\/enhancedkycresponse"},"doc://org.cocoapods.SmileID/documentation/SmileID/DocumentVerificationResultDelegate":{"url":"\/documentation\/smileid\/documentverificationresultdelegate","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentVerificationResultDelegate"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DocumentVerificationResultDelegate","navigatorTitle":[{"text":"DocumentVerificationResultDelegate","kind":"identifier"}],"title":"DocumentVerificationResultDelegate"},"doc://org.cocoapods.SmileID/documentation/SmileID/ConsentInfo":{"url":"\/documentation\/smileid\/consentinfo","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentInfo"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ConsentInfo","navigatorTitle":[{"text":"ConsentInfo","kind":"identifier"}],"title":"ConsentInfo"},"doc://org.cocoapods.SmileID/documentation/SmileID/FontType":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/FontType","title":"FontType","type":"topic","navigatorTitle":[{"text":"FontType","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FontType","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/smileid\/fonttype","role":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/Swift":{"url":"\/documentation\/smileid\/swift","abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Swift","title":"Swift"},"doc://org.cocoapods.SmileID/documentation/SmileID/ImageLinks":{"url":"\/documentation\/smileid\/imagelinks","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageLinks"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ImageLinks","navigatorTitle":[{"text":"ImageLinks","kind":"identifier"}],"title":"ImageLinks"},"doc://org.cocoapods.SmileID/documentation/SmileID/SubmitBvnTotpResponse":{"url":"\/documentation\/smileid\/submitbvntotpresponse","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SubmitBvnTotpResponse"}],"navigatorTitle":[{"kind":"identifier","text":"SubmitBvnTotpResponse"}],"title":"SubmitBvnTotpResponse","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SubmitBvnTotpResponse","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileButton":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SmileButton","kind":"identifier"}],"url":"\/documentation\/smileid\/smilebutton","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileButton","abstract":[],"title":"SmileButton","navigatorTitle":[{"kind":"identifier","text":"SmileButton"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/BankCode":{"url":"\/documentation\/smileid\/bankcode","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"BankCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BankCode","navigatorTitle":[{"text":"BankCode","kind":"identifier"}],"title":"BankCode"},"doc://org.cocoapods.SmileID/documentation/SmileID/IdSelection":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdSelection"}],"url":"\/documentation\/smileid\/idselection","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/IdSelection","abstract":[],"title":"IdSelection","navigatorTitle":[{"kind":"identifier","text":"IdSelection"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/UploadResponse":{"type":"topic","kind":"symbol","url":"\/documentation\/smileid\/uploadresponse","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/UploadResponse","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UploadResponse"}],"role":"symbol","navigatorTitle":[{"text":"UploadResponse","kind":"identifier"}],"title":"UploadResponse","abstract":[]},"doc://org.cocoapods.SmileID/documentation/SmileID/ProcessingInProgressScreen":{"title":"ProcessingInProgressScreen","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProcessingInProgressScreen"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ProcessingInProgressScreen","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProcessingInProgressScreen","url":"\/documentation\/smileid\/processinginprogressscreen","abstract":[],"role":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/ActivityIndicator":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivityIndicator"}],"url":"\/documentation\/smileid\/activityindicator","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ActivityIndicator","abstract":[],"title":"ActivityIndicator","navigatorTitle":[{"kind":"identifier","text":"ActivityIndicator"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/ProcessingErrorScreen":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProcessingErrorScreen","role":"symbol","url":"\/documentation\/smileid\/processingerrorscreen","abstract":[],"title":"ProcessingErrorScreen","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingErrorScreen","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ProcessingErrorScreen","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/SmartSelfieInstructionsScreen":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmartSelfieInstructionsScreen","url":"\/documentation\/smileid\/smartselfieinstructionsscreen","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SmartSelfieInstructionsScreen","kind":"identifier"}],"abstract":[{"text":"Displays instructions to the user for how to take a good quality selfie","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SmartSelfieInstructionsScreen","kind":"identifier"}],"title":"SmartSelfieInstructionsScreen","kind":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID":{"url":"\/documentation\/smileid","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID","title":"SmileID","type":"topic","abstract":[],"role":"collection"},"doc://org.cocoapods.SmileID/documentation/SmileID/RequiredField":{"navigatorTitle":[{"text":"RequiredField","kind":"identifier"}],"abstract":[],"url":"\/documentation\/smileid\/requiredfield","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/RequiredField","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequiredField","kind":"identifier"}],"title":"RequiredField","kind":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/SearchableDropdownSelector":{"navigatorTitle":[{"text":"SearchableDropdownSelector","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smileid\/searchabledropdownselector","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SearchableDropdownSelector","kind":"symbol","type":"topic","title":"SearchableDropdownSelector","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchableDropdownSelector"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/ValidDocument":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ValidDocument","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidDocument"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidDocument"}],"title":"ValidDocument","kind":"symbol","url":"\/documentation\/smileid\/validdocument","abstract":[]},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileIDLocalizableStrings":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SmileIDLocalizableStrings","kind":"identifier"}],"url":"\/documentation\/smileid\/smileidlocalizablestrings","abstract":[{"type":"text","text":"Encapsulates the bundle and tablename of the Localizable.strings file to be used within the SDK"}],"role":"symbol","navigatorTitle":[{"text":"SmileIDLocalizableStrings","kind":"identifier"}],"title":"SmileIDLocalizableStrings","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDLocalizableStrings"},"doc://org.cocoapods.SmileID/documentation/SmileID/SubmitBvnTotpRequest":{"type":"topic","url":"\/documentation\/smileid\/submitbvntotprequest","title":"SubmitBvnTotpRequest","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SubmitBvnTotpRequest","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"SubmitBvnTotpRequest","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SubmitBvnTotpRequest"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileIDErrorResponse":{"url":"\/documentation\/smileid\/smileiderrorresponse","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SmileIDErrorResponse"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDErrorResponse","navigatorTitle":[{"text":"SmileIDErrorResponse","kind":"identifier"}],"title":"SmileIDErrorResponse"},"doc://org.cocoapods.SmileID/documentation/SmileID/AuthenticationResponse":{"url":"\/documentation\/smileid\/authenticationresponse","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/AuthenticationResponse","navigatorTitle":[{"text":"AuthenticationResponse","kind":"identifier"}],"title":"AuthenticationResponse"},"doc://org.cocoapods.SmileID/documentation/SmileID/SuspectUser":{"url":"\/documentation\/smileid\/suspectuser","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SuspectUser"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SuspectUser","navigatorTitle":[{"text":"SuspectUser","kind":"identifier"}],"title":"SuspectUser"},"doc://org.cocoapods.SmileID/documentation/SmileID/CountryCodeToCountryInfo":{"url":"\/documentation\/smileid\/countrycodetocountryinfo","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CountryCodeToCountryInfo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/CountryCodeToCountryInfo","navigatorTitle":[{"text":"CountryCodeToCountryInfo","kind":"identifier"}],"title":"CountryCodeToCountryInfo"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileID":{"navigatorTitle":[{"kind":"identifier","text":"SmileID"}],"abstract":[],"url":"\/documentation\/smileid\/smileid","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileID","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileID"}],"title":"SmileID","kind":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/ConsentScreen":{"navigatorTitle":[{"text":"ConsentScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"Consent screen for SmileID"}],"url":"\/documentation\/smileid\/consentscreen","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ConsentScreen","role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentScreen"}],"title":"ConsentScreen","kind":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/OrchestratedConsentScreen":{"url":"\/documentation\/smileid\/orchestratedconsentscreen","title":"OrchestratedConsentScreen","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"OrchestratedConsentScreen","kind":"identifier"}],"abstract":[{"text":"Responsible for showing the consent screen and the consent denied (try again) screens.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"OrchestratedConsentScreen","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/OrchestratedConsentScreen","kind":"symbol","type":"topic"},"doc://org.cocoapods.SmileID/documentation/SmileID/AvailableIdType":{"url":"\/documentation\/smileid\/availableidtype","abstract":[{"type":"text","text":"The  idTypeKey field is not populated\/returned by the API response, hence it being marked as"},{"text":" ","type":"text"},{"text":"mutable. However, it should be populated before usage of this class\/when the response gets decoded","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AvailableIdType"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/AvailableIdType","navigatorTitle":[{"text":"AvailableIdType","kind":"identifier"}],"title":"AvailableIdType"},"doc://org.cocoapods.SmileID/documentation/SmileID/BvnVerificationMode":{"url":"\/documentation\/smileid\/bvnverificationmode","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BvnVerificationMode"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BvnVerificationMode","navigatorTitle":[{"text":"BvnVerificationMode","kind":"identifier"}],"title":"BvnVerificationMode"},"doc://org.cocoapods.SmileID/documentation/SmileID/IdType":{"url":"\/documentation\/smileid\/idtype","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"IdType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/IdType","navigatorTitle":[{"text":"IdType","kind":"identifier"}],"title":"IdType"},"doc://org.cocoapods.SmileID/documentation/SmileID/HostedWeb":{"url":"\/documentation\/smileid\/hostedweb","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HostedWeb"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/HostedWeb","navigatorTitle":[{"text":"HostedWeb","kind":"identifier"}],"title":"HostedWeb"},"doc://org.cocoapods.SmileID/documentation/SmileID/BvnTotpResponse":{"url":"\/documentation\/smileid\/bvntotpresponse","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"BvnTotpResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BvnTotpResponse","navigatorTitle":[{"text":"BvnTotpResponse","kind":"identifier"}],"title":"BvnTotpResponse"},"doc://org.cocoapods.SmileID/documentation/SmileID/ImageCaptureConfirmationDialog":{"type":"topic","url":"\/documentation\/smileid\/imagecaptureconfirmationdialog","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageCaptureConfirmationDialog"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ImageCaptureConfirmationDialog","abstract":[{"type":"text","text":"A dialog that shows a preview of the image captured by the camera and asks the user to confirm"},{"text":" ","type":"text"},{"text":"that the image is of acceptable quality.","type":"text"}],"title":"ImageCaptureConfirmationDialog","kind":"symbol","navigatorTitle":[{"text":"ImageCaptureConfirmationDialog","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/Actions":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Actions","type":"topic","url":"\/documentation\/smileid\/actions","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Actions","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","title":"Actions","navigatorTitle":[{"kind":"identifier","text":"Actions"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/Foundation":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"Foundation","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Foundation","url":"\/documentation\/smileid\/foundation"},"doc://org.cocoapods.SmileID/documentation/SmileID/ActionResult":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ActionResult","type":"topic","url":"\/documentation\/smileid\/actionresult","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionResult"}],"role":"symbol","abstract":[],"kind":"symbol","title":"ActionResult","navigatorTitle":[{"text":"ActionResult","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/ProcessingState":{"url":"\/documentation\/smileid\/processingstate","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProcessingState"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProcessingState","navigatorTitle":[{"text":"ProcessingState","kind":"identifier"}],"title":"ProcessingState"},"doc://org.cocoapods.SmileID/documentation/SmileID/IdTypeKeyToAvailableIdType":{"url":"\/documentation\/smileid\/idtypekeytoavailableidtype","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"IdTypeKeyToAvailableIdType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/IdTypeKeyToAvailableIdType","navigatorTitle":[{"text":"IdTypeKeyToAvailableIdType","kind":"identifier"}],"title":"IdTypeKeyToAvailableIdType"},"doc://org.cocoapods.SmileID/documentation/SmileID/AspectRatioRoundedRectangle":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AspectRatioRoundedRectangle"}],"url":"\/documentation\/smileid\/aspectratioroundedrectangle","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/AspectRatioRoundedRectangle","abstract":[],"title":"AspectRatioRoundedRectangle","navigatorTitle":[{"text":"AspectRatioRoundedRectangle","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/ProductsConfigRequest":{"url":"\/documentation\/smileid\/productsconfigrequest","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProductsConfigRequest"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProductsConfigRequest","navigatorTitle":[{"text":"ProductsConfigRequest","kind":"identifier"}],"title":"ProductsConfigRequest"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileIDResourcesHelper":{"url":"\/documentation\/smileid\/smileidresourceshelper","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDResourcesHelper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SmileIDResourcesHelper"}],"title":"SmileIDResourcesHelper","navigatorTitle":[{"text":"SmileIDResourcesHelper","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/DocumentVerificationJobStatusResponse":{"url":"\/documentation\/smileid\/documentverificationjobstatusresponse","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentVerificationJobStatusResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DocumentVerificationJobStatusResponse","navigatorTitle":[{"text":"DocumentVerificationJobStatusResponse","kind":"identifier"}],"title":"DocumentVerificationJobStatusResponse"},"doc://org.cocoapods.SmileID/documentation/SmileID/EpilogueFont":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EpilogueFont","title":"EpilogueFont","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EpilogueFont"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EpilogueFont"}],"kind":"symbol","abstract":[],"url":"\/documentation\/smileid\/epiloguefont","role":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmartSelfieJobStatusResponse":{"type":"topic","url":"\/documentation\/smileid\/smartselfiejobstatusresponse","title":"SmartSelfieJobStatusResponse","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmartSelfieJobStatusResponse","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SmartSelfieJobStatusResponse"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmartSelfieJobStatusResponse"},"doc://org.cocoapods.SmileID/documentation/SmileID/ImageType":{"type":"topic","url":"\/documentation\/smileid\/imagetype","title":"ImageType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageType","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ImageType"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ImageType"},"doc://org.cocoapods.SmileID/documentation/SmileID/ValidDocumentsResponse":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidDocumentsResponse"}],"role":"symbol","url":"\/documentation\/smileid\/validdocumentsresponse","kind":"symbol","type":"topic","title":"ValidDocumentsResponse","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ValidDocumentsResponse","abstract":[],"navigatorTitle":[{"text":"ValidDocumentsResponse","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/PartnerParams":{"url":"\/documentation\/smileid\/partnerparams","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PartnerParams"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/PartnerParams","navigatorTitle":[{"text":"PartnerParams","kind":"identifier"}],"title":"PartnerParams"},"doc://org.cocoapods.SmileID/documentation/SmileID/BiometricKycJobStatusResponse":{"url":"\/documentation\/smileid\/biometrickycjobstatusresponse","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BiometricKycJobStatusResponse"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BiometricKycJobStatusResponse","navigatorTitle":[{"text":"BiometricKycJobStatusResponse","kind":"identifier"}],"title":"BiometricKycJobStatusResponse"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmartSelfieResultDelegate":{"type":"topic","url":"\/documentation\/smileid\/smartselfieresultdelegate","title":"SmartSelfieResultDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SmartSelfieResultDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"SmartSelfieResultDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmartSelfieResultDelegate"},"doc://org.cocoapods.SmileID/documentation/SmileID/URLUploadSessionPublisher":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"URLUploadSessionPublisher"}],"kind":"symbol","url":"\/documentation\/smileid\/urluploadsessionpublisher","title":"URLUploadSessionPublisher","navigatorTitle":[{"text":"URLUploadSessionPublisher","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLUploadSessionPublisher","role":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/Combine":{"abstract":[],"title":"Combine","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Combine","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/smileid\/combine"},"doc://org.cocoapods.SmileID/documentation/SmileID/BiometricKycJobResult":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"BiometricKycJobResult","kind":"identifier"}],"title":"BiometricKycJobResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BiometricKycJobResult"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BiometricKycJobResult","url":"\/documentation\/smileid\/biometrickycjobresult"},"doc://org.cocoapods.SmileID/documentation/SmileID/UploadImageInfo":{"type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UploadImageInfo"}],"url":"\/documentation\/smileid\/uploadimageinfo","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UploadImageInfo"}],"title":"UploadImageInfo","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/UploadImageInfo"},"doc://org.cocoapods.SmileID/documentation/SmileID/RadioGroupSelector":{"title":"RadioGroupSelector","navigatorTitle":[{"text":"RadioGroupSelector","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/RadioGroupSelector","url":"\/documentation\/smileid\/radiogroupselector","abstract":[],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RadioGroupSelector","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileIDVersionNumber":{"url":"\/documentation\/smileid\/smileidversionnumber","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"SmileIDVersionNumber","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDVersionNumber","title":"SmileIDVersionNumber"},"doc://org.cocoapods.SmileID/documentation/SmileID/IdTypes":{"url":"\/documentation\/smileid\/idtypes","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/IdTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdTypes"}],"role":"symbol","abstract":[{"type":"text","text":"Country Code to ID Type (e.g. {“ZA”: [“NATIONAL_ID_NO_PHOTO”]}"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdTypes","kind":"identifier"}],"title":"IdTypes"},"doc://org.cocoapods.SmileID/documentation/SmileID/PrepUploadResponse":{"role":"symbol","url":"\/documentation\/smileid\/prepuploadresponse","title":"PrepUploadResponse","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/PrepUploadResponse","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"PrepUploadResponse","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrepUploadResponse"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/HTTPQueryParameters":{"url":"\/documentation\/smileid\/httpqueryparameters","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPQueryParameters"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/HTTPQueryParameters","navigatorTitle":[{"kind":"identifier","text":"HTTPQueryParameters"}],"type":"topic","abstract":[],"title":"HTTPQueryParameters","kind":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/DocumentCaptureInstructionsScreen":{"url":"\/documentation\/smileid\/documentcaptureinstructionsscreen","title":"DocumentCaptureInstructionsScreen","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentCaptureInstructionsScreen"}],"abstract":[{"text":"Instructions for taking a good quality document photo. Optionally, allows user to select a photo from their gallery.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DocumentCaptureInstructionsScreen","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DocumentCaptureInstructionsScreen","kind":"symbol","type":"topic"},"doc://org.cocoapods.SmileID/documentation/SmileID/generateJobId()":{"url":"\/documentation\/smileid\/generatejobid()","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"generateJobId","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/generateJobId()","title":"generateJobId()"},"doc://org.cocoapods.SmileID/documentation/SmileID/EnhancedKycRequest":{"type":"topic","url":"\/documentation\/smileid\/enhancedkycrequest","title":"EnhancedKycRequest","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"EnhancedKycRequest","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"EnhancedKycRequest","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedKycRequest"},"doc://org.cocoapods.SmileID/documentation/SmileID/JobType":{"url":"\/documentation\/smileid\/jobtype","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/JobType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JobType"}],"title":"JobType","navigatorTitle":[{"kind":"identifier","text":"JobType"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/URLUploadSessionPublisherImplementation":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"URLUploadSessionPublisherImplementation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smileid\/urluploadsessionpublisherimplementation","title":"URLUploadSessionPublisherImplementation","navigatorTitle":[{"text":"URLUploadSessionPublisherImplementation","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLUploadSessionPublisherImplementation","role":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/ConsentDeniedScreen":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ConsentDeniedScreen","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConsentDeniedScreen"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ConsentDeniedScreen","kind":"identifier"}],"title":"ConsentDeniedScreen","kind":"symbol","url":"\/documentation\/smileid\/consentdeniedscreen","abstract":[{"type":"text","text":"Asks user to confirm that they do actually want to deny consent"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/SmartSelfieJobResult":{"url":"\/documentation\/smileid\/smartselfiejobresult","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmartSelfieJobResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SmartSelfieJobResult"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmartSelfieJobResult","title":"SmartSelfieJobResult","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/BvnTotpModeRequest":{"url":"\/documentation\/smileid\/bvntotpmoderequest","abstract":[],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BvnTotpModeRequest","type":"topic","role":"symbol","title":"BvnTotpModeRequest","navigatorTitle":[{"text":"BvnTotpModeRequest","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"BvnTotpModeRequest","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/BiometricKycResultDelegate":{"url":"\/documentation\/smileid\/biometrickycresultdelegate","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BiometricKycResultDelegate"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BiometricKycResultDelegate","navigatorTitle":[{"text":"BiometricKycResultDelegate","kind":"identifier"}],"title":"BiometricKycResultDelegate"},"doc://org.cocoapods.SmileID/documentation/SmileID/PrepUploadRequest":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/PrepUploadRequest","kind":"symbol","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PrepUploadRequest","kind":"identifier"}],"navigatorTitle":[{"text":"PrepUploadRequest","kind":"identifier"}],"title":"PrepUploadRequest","url":"\/documentation\/smileid\/prepuploadrequest"},"doc://org.cocoapods.SmileID/documentation/SmileID/Antifraud":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Antifraud","title":"Antifraud","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Antifraud"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Antifraud","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/smileid\/antifraud","role":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/SwiftUI":{"abstract":[],"title":"SwiftUI","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SwiftUI","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/smileid\/swiftui"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileIDError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SmileIDError"}],"navigatorTitle":[{"text":"SmileIDError","kind":"identifier"}],"title":"SmileIDError","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDError","type":"topic","url":"\/documentation\/smileid\/smileiderror","abstract":[],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileIDService":{"url":"\/documentation\/smileid\/smileidservice","abstract":[],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDService","type":"topic","role":"symbol","title":"SmileIDService","navigatorTitle":[{"text":"SmileIDService","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SmileIDService"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/ServicesResponse":{"url":"\/documentation\/smileid\/servicesresponse","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ServicesResponse"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ServicesResponse","navigatorTitle":[{"text":"ServicesResponse","kind":"identifier"}],"title":"ServicesResponse"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileIdTheme":{"title":"SmileIdTheme","abstract":[],"url":"\/documentation\/smileid\/smileidtheme","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileIdTheme","kind":"identifier"}],"navigatorTitle":[{"text":"SmileIdTheme","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIdTheme","role":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/AuthenticationRequest":{"type":"topic","title":"AuthenticationRequest","navigatorTitle":[{"kind":"identifier","text":"AuthenticationRequest"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/AuthenticationRequest","url":"\/documentation\/smileid\/authenticationrequest","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationRequest"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The Auth Smile request. Auth Smile serves multiple purposes:"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/DocumentVerificationJobResult":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DocumentVerificationJobResult","title":"DocumentVerificationJobResult","url":"\/documentation\/smileid\/documentverificationjobresult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentVerificationJobResult","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"DocumentVerificationJobResult","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/Config":{"navigatorTitle":[{"kind":"identifier","text":"Config"}],"abstract":[],"url":"\/documentation\/smileid\/config","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Config","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Config","kind":"identifier"}],"title":"Config","kind":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/EnhancedDocumentVerificationJobResult":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EnhancedDocumentVerificationJobResult"}],"role":"symbol","url":"\/documentation\/smileid\/enhanceddocumentverificationjobresult","kind":"symbol","title":"EnhancedDocumentVerificationJobResult","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedDocumentVerificationJobResult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EnhancedDocumentVerificationJobResult","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/URLDelegate":{"url":"\/documentation\/smileid\/urldelegate","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"URLDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate","navigatorTitle":[{"text":"URLDelegate","kind":"identifier"}],"title":"URLDelegate"},"doc://org.cocoapods.SmileID/documentation/SmileID/ProcessingScreen":{"kind":"symbol","url":"\/documentation\/smileid\/processingscreen","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProcessingScreen","role":"symbol","abstract":[{"text":"This screen represents a generic Processing state. It has 3 sub-states: In Progress, Success, and","type":"text"},{"text":" ","type":"text"},{"text":"Error. These sub-states are represented by the [processingState] parameter.","type":"text"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingScreen"}],"navigatorTitle":[{"text":"ProcessingScreen","kind":"identifier"}],"title":"ProcessingScreen"},"doc://org.cocoapods.SmileID/documentation/SmileID/DocumentCaptureScreen":{"abstract":[{"type":"text","text":"This handles Instructions + Capture + Confirmation for a single side of a document"}],"title":"DocumentCaptureScreen","role":"symbol","url":"\/documentation\/smileid\/documentcapturescreen","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DocumentCaptureScreen","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentCaptureScreen","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DocumentCaptureScreen"},"doc://org.cocoapods.SmileID/documentation/SmileID/EnhancedDocumentVerificationJobStatusResponse":{"type":"topic","title":"EnhancedDocumentVerificationJobStatusResponse","role":"symbol","url":"\/documentation\/smileid\/enhanceddocumentverificationjobstatusresponse","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnhancedDocumentVerificationJobStatusResponse"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedDocumentVerificationJobStatusResponse","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EnhancedDocumentVerificationJobStatusResponse"}],"kind":"symbol"},"doc://org.cocoapods.SmileID/documentation/SmileID/BvnTotpModeResponse":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BvnTotpModeResponse","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BvnTotpModeResponse"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BvnTotpModeResponse"}],"type":"topic","url":"\/documentation\/smileid\/bvntotpmoderesponse","abstract":[],"title":"BvnTotpModeResponse"},"doc://org.cocoapods.SmileID/documentation/SmileID/CountryInfo":{"url":"\/documentation\/smileid\/countryinfo","abstract":[{"type":"text","text":"The countryCode field is not populated\/returned by the API response, hence it being marked as"},{"text":" ","type":"text"},{"text":"mutable. However, it should be populated before usage of this class\/when the response gets decoded.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The same applies to availableIdTypes"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CountryInfo"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/CountryInfo","navigatorTitle":[{"kind":"identifier","text":"CountryInfo"}],"title":"CountryInfo"},"doc://org.cocoapods.SmileID/documentation/SmileID/EnhancedKycAsyncResponse":{"url":"\/documentation\/smileid\/enhancedkycasyncresponse","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"EnhancedKycAsyncResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedKycAsyncResponse","navigatorTitle":[{"kind":"identifier","text":"EnhancedKycAsyncResponse"}],"title":"EnhancedKycAsyncResponse"},"doc://org.cocoapods.SmileID/documentation/SmileID/SelfieViewModel":{"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelfieViewModel"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SelfieViewModel","kind":"identifier"}],"title":"SelfieViewModel","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SelfieViewModel","url":"\/documentation\/smileid\/selfieviewmodel"},"doc://org.cocoapods.SmileID/documentation/SmileID/UploadRequest":{"type":"topic","kind":"symbol","url":"\/documentation\/smileid\/uploadrequest","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/UploadRequest","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UploadRequest"}],"role":"symbol","navigatorTitle":[{"text":"UploadRequest","kind":"identifier"}],"title":"UploadRequest","abstract":[]},"doc://org.cocoapods.SmileID/documentation/SmileID/SelfieCaptureScreen":{"role":"symbol","url":"\/documentation\/smileid\/selfiecapturescreen","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SelfieCaptureScreen"}],"abstract":[{"type":"text","text":"The actual selfie capture screen, which shows the camera preview and the progress indicator"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SelfieCaptureScreen","title":"SelfieCaptureScreen","navigatorTitle":[{"kind":"identifier","text":"SelfieCaptureScreen"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/IdInfo":{"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/IdInfo","type":"topic","url":"\/documentation\/smileid\/idinfo","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdInfo"}],"role":"symbol","abstract":[],"kind":"symbol","title":"IdInfo","navigatorTitle":[{"kind":"identifier","text":"IdInfo"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/generateUserId()":{"url":"\/documentation\/smileid\/generateuserid()","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generateUserId"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/generateUserId()","title":"generateUserId()"},"doc://org.cocoapods.SmileID/documentation/SmileID/BvnTotpRequest":{"type":"topic","title":"BvnTotpRequest","abstract":[],"url":"\/documentation\/smileid\/bvntotprequest","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/BvnTotpRequest","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BvnTotpRequest"}],"navigatorTitle":[{"text":"BvnTotpRequest","kind":"identifier"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/LocalStorage":{"url":"\/documentation\/smileid\/localstorage","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LocalStorage","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/LocalStorage","navigatorTitle":[{"text":"LocalStorage","kind":"identifier"}],"title":"LocalStorage"},"doc://org.cocoapods.SmileID/documentation/SmileID/SmileIDVersionString":{"url":"\/documentation\/smileid\/smileidversionstring","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"SmileIDVersionString","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDVersionString","title":"SmileIDVersionString"},"doc://org.cocoapods.SmileID/documentation/SmileID/ProductsConfigResponse":{"kind":"symbol","abstract":[],"url":"\/documentation\/smileid\/productsconfigresponse","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/ProductsConfigResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ProductsConfigResponse","kind":"identifier"}],"type":"topic","title":"ProductsConfigResponse","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProductsConfigResponse"}]},"doc://org.cocoapods.SmileID/documentation/SmileID/JobResult":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JobResult","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"JobResult","kind":"identifier"}],"title":"JobResult","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/JobResult","url":"\/documentation\/smileid\/jobresult"},"doc://org.cocoapods.SmileID/documentation/SmileID/DefaultServiceHeaderProvider":{"url":"\/documentation\/smileid\/defaultserviceheaderprovider","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DefaultServiceHeaderProvider","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/DefaultServiceHeaderProvider","navigatorTitle":[{"text":"DefaultServiceHeaderProvider","kind":"identifier"}],"title":"DefaultServiceHeaderProvider"},"doc://org.cocoapods.SmileID/documentation/SmileID/HTTPHeader":{"url":"\/documentation\/smileid\/httpheader","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HTTPHeader"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/HTTPHeader","navigatorTitle":[{"text":"HTTPHeader","kind":"identifier"}],"title":"HTTPHeader"},"doc://org.cocoapods.SmileID/documentation/SmileID/EnhancedDocumentVerificationResultDelegate":{"url":"\/documentation\/smileid\/enhanceddocumentverificationresultdelegate","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"EnhancedDocumentVerificationResultDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/EnhancedDocumentVerificationResultDelegate","navigatorTitle":[{"text":"EnhancedDocumentVerificationResultDelegate","kind":"identifier"}],"title":"EnhancedDocumentVerificationResultDelegate"},"doc://org.cocoapods.SmileID/documentation/SmileID/Country":{"role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/Country","title":"Country","type":"topic","url":"\/documentation\/smileid\/country","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Country","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Country"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate"],"title":"Classes"},{"identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDVersionNumber","doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/SmileIDVersionString"],"title":"Variables"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"URLDelegate","path":"\/references\/doc:~1~1org.cocoapods.SmileID~1documentation~1SmileID~1URLDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"URLDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SmileID~1documentation~1SmileID~1URLDelegate\/fragments","op":"replace"}]}]}