default_platform(:ios)

platform :ios do

desc "Run unit tests"
  lane :unit_tests do
    clear_derived_data
  scan(
    project: "SmileIdentity.xcodeproj",
    scheme: "SmileIdentityTests",
    derived_data_path: "temp",
    clean: true)
  end

desc "Release to TestFlight"
  lane :releaseapp do
    release_build

    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_content: ENV["APPSTORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: true,
      duration: 1200
    )

    upload_to_testflight(
      api_key: api_key,
      distribute_external: false,
      notify_external_testers: false,
    )
  end

  private_lane :release_build do
    clear_derived_data
      
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_content: ENV["APPSTORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: true,
      duration: 1200
    )
    
    create_keychain(
      name: "CI",
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  
    match(
      type: "appstore",
      keychain_name: "CI",
      keychain_password: ENV["MATCH_PASSWORD"],
      readonly: is_ci,
      api_key: api_key,
      verbose: true
    )
  
    build_app(
      use_system_scm: true,
      project: "SmileIdentity.xcodeproj",
      scheme: "SmileIdentity-Example",
      export_method: "app-store"
    )

    increment_build_number
  end
end
