default_platform(:ios)

platform :ios do

desc "Release to TestFlight"
  lane :releaseapp do
    cocoapods(clean_install: true)
    release_build

    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_content: ENV["APPSTORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: true,
      duration: 1200
    )

    upload_to_testflight(
      api_key: api_key,
      distribute_external: false,
      notify_external_testers: false,
    )
  end

  lane :run_match do
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_content: ENV["APPSTORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: true,
      duration: 1200
    )
    
    create_keychain(
      name: "CI",
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  
    match(
      type: "appstore",
      keychain_name: "CI",
      keychain_password: ENV["MATCH_PASSWORD"],
      readonly: is_ci,
      api_key: api_key,
      verbose: true
    )
  end

  private_lane :release_build do
    run_match
    clear_derived_data
  
    build_app(
      use_system_scm: true,
      workspace: "SmileIdentity.xcworkspace",
      scheme: "SmileIdentity-Example",
      export_method: "app-store"
    )

    increment_build
  end
  
  private_lane :increment_build do
    build_number = `git rev-list HEAD --count`.to_i
    increment_build_number(build_number: build_number)
  end
end
