default_platform(:ios)

platform :ios do

desc "Run unit tests"
  lane :unit_tests do
    clear_derived_data
  scan(
    project: "SmileIdentity.xcodeproj",
    scheme: "SmileIdentityTests",
    derived_data_path: "temp",
    clean: true)
  end

desc "Release to TestFlight"
  lane :testflight do
    release_build

    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_content: ENV["APPSTORE_CONNECT_PRIVATE_KEY"],
      duration: 1200
    )

    upload_to_testflight(
      api_key: api_key,
      distribute_external: false,
      notify_external_testers: false,
    )

    slack_notifications(
      displayMessage: "Deployed Smile Identity sample app to TestFlight. :fire: ",
      slackChannel: "#")
  end

  private_lane :release_build do
    clear_derived_data
      
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_content: ENV["APPSTORE_CONNECT_PRIVATE_KEY"],
      duration: 1200
    )
    
    create_keychain(
      name: "CI",
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  
    match(
      type: "appstore",
      keychain_name: "CI",
      keychain_password: ENV["MATCH_PASSWORD"],
      readonly: is_ci,
      api_key: api_key,
      verbose: true
    )
  
    build_app(
      use_system_scm: true,
      workspace: "SmileIdentity.xcodeproj",
      scheme: "SmileIdentity-Example",
      export_method: "app-store"
    )
  end

  private_lane :slack_notifications do |values|
    displayMessage  = values[:displayMessage]
    slackChannel  = values[:slackChannel]
    puts displayMessage
    puts slackChannel
    post_to_slack(
      api_token: ENV['MOBILE_SLACK_BOT_TOKEN'],
      message: displayMessage,
      channel: slackChannel, 
      success: true,  
      payload: { 
        "Build Date" => Time.new.to_s,
        "Built by" => "Github Actions"
      },
      default_payloads: [
        :git_branch,
        :lane,
        :git_author,
        :test_result,
        :last_git_commit_hash,
        :last_git_commit_message],
        attachment_properties: { 
        thumb_url: "https://fastlane.tools/assets/img/fastlane_icon.png"
      }
    )
    end
end
