{"identifier":{"url":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLDelegate","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smileid\/urldelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smileid\/urldelegate"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate\/init(subject:)"]},{"identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate\/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)"],"title":"Instance Methods"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SmileID\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/org.cocoapods.SmileID\/objc(pl)NSURLSessionDelegate","doc:\/\/org.cocoapods.SmileID\/objc(pl)NSURLSessionTaskDelegate","doc:\/\/org.cocoapods.SmileID\/objc(pl)NSObject","doc:\/\/org.cocoapods.SmileID\/s7CVarArgP","doc:\/\/org.cocoapods.SmileID\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SmileID\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SmileID\/SQ","doc:\/\/org.cocoapods.SmileID\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"metadata":{"modules":[{"name":"SmileID"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"URLDelegate","kind":"identifier"}],"externalID":"c:@M@SmileID@objc(cs)URLDelegate","navigatorTitle":[{"kind":"identifier","text":"URLDelegate"}],"symbolKind":"class","roleHeading":"Class","title":"URLDelegate"},"sections":[],"references":{"doc://org.cocoapods.SmileID/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.SmileID\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.SmileID/objc(pl)NSURLSessionTaskDelegate":{"identifier":"doc:\/\/org.cocoapods.SmileID\/objc(pl)NSURLSessionTaskDelegate","title":"NSURLSessionTaskDelegate","type":"unresolvable"},"doc://org.cocoapods.SmileID/objc(pl)NSURLSessionDelegate":{"identifier":"doc:\/\/org.cocoapods.SmileID\/objc(pl)NSURLSessionDelegate","title":"Foundation.URLSessionDelegate","type":"unresolvable"},"doc://org.cocoapods.SmileID/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.SmileID\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.SmileID/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SmileID\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.SmileID/documentation/SmileID/URLDelegate/init(subject:)":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate\/init(subject:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"subject"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7Combine18PassthroughSubjectC","text":"PassthroughSubject","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"UploadResponse","preciseIdentifier":"s:7SmileID14UploadResponseO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">)"}],"url":"\/documentation\/smileid\/urldelegate\/init(subject:)","title":"init(subject:)"},"doc://org.cocoapods.SmileID/documentation/SmileID":{"url":"\/documentation\/smileid","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID","title":"SmileID","type":"topic","abstract":[],"role":"collection"},"doc://org.cocoapods.SmileID/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SmileID\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.SmileID/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SmileID\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.SmileID/documentation/SmileID/URLDelegate/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)":{"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate\/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLSessionTask","text":"URLSessionTask","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didSendBodyData","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"totalBytesSent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"totalBytesExpectedToSend"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","kind":"identifier"}],"url":"\/documentation\/smileid\/urldelegate\/urlsession(_:task:didsendbodydata:totalbytessent:totalbytesexpectedtosend:)","title":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)"},"doc://org.cocoapods.SmileID/SH":{"identifier":"doc:\/\/org.cocoapods.SmileID\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.SmileID/documentation/SmileID/URLDelegate":{"url":"\/documentation\/smileid\/urldelegate","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"URLDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate","navigatorTitle":[{"text":"URLDelegate","kind":"identifier"}],"title":"URLDelegate"},"doc://org.cocoapods.SmileID/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SmileID\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"URLDelegate"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"URLDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"URLDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.SmileID\/documentation\/SmileID\/URLDelegate\/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SmileID\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SmileID\/objc(pl)NSURLSessionTaskDelegate"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"URLDelegate"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SmileID~1documentation~1SmileID~1URLDelegate~1urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)\/title","value":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SmileID~1documentation~1SmileID~1URLDelegate~1urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)\/fragments"},{"op":"replace","value":"URLDelegate","path":"\/references\/doc:~1~1org.cocoapods.SmileID~1documentation~1SmileID~1URLDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"URLDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SmileID~1documentation~1SmileID~1URLDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}