// swiftlint:disable all
// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

protocol ArkanaKeysGlobalProtocol {
    var sENTRY_DSN: String { get }
}

protocol ArkanaKeysEnvironmentProtocol {
}
