// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol ArkanaKeysGlobalProtocol {
    var sENTRY_DSN: String { get }
}

public protocol ArkanaKeysEnvironmentProtocol {
}
