name: Build and Release Framework

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-release:
    # TODO: Change back to macos-latest once it points to macOS 14 (Q2 '24)
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Install xcodeproj
      run: sudo gem install xcodeproj

    - name: Update Compile Sources
      run: ruby ./Scripts/update_compile_sources.rb

    - name: Build Framework
      run: |
        chmod +x ./Scripts/build_frameworks.sh
        ./Scripts/build_frameworks.sh
    
    - name: Archive Framework
      run: zip -r ./SmileID.xcframework.zip ./Frameworks/SmileID.xcframework
      
    - name: Upload Framework to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./SmileID.xcframework.zip
        asset_name: SmileID.framework.zip
        asset_content_type: application/zip
