name: Lint, Build, Test
on:
  pull_request:
  workflow_dispatch:

jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    name: Code quality Checks

    steps:
     - uses: actions/checkout@v3
     - name: Danger
       uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.15.0
       with:
            args: --failOnErrors --no-publish-check
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: macos-latest
    name: Unit Tests

    steps:
     - name: Checkout
       uses: actions/checkout@v3
       
     - name: Setup environment
       run: | 
          bundle install
     
     - name: Select Xcode Version
       uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable

     - name: Run tests
       run: |
         cd Example
         bundle exec fastlane unit_tests
       env:
         FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 10
