name: Release iOS SDK

on:
  workflow_dispatch:
    inputs:
      version_override:
        description: 'The version to release. If not specified, the version will be inferred'
        type: string
        required: false
        default: ''
      bump_version:
        description: 'Whether to automatically bump and commit the version after the release'
        type: boolean
        required: true
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run-build-checks:
   uses: ./.github/workflows/sdk-primary.yml