name: Release iOS SDK

on:
  workflow_dispatch:
    inputs:
      version_override:
        type: string
        description: 'The version to release. If not specified, the version will be inferred'
        required: false
        default: ''
      bump_version:
        type: boolean
        description: 'Whether to automatically bump and commit the version after the release'
        required: true
        default: true

jobs:
  run-build-checks:
   uses: ./.github/workflows/sdk-primary.yml
   with:
    version_override: ${{ inputs.version_override }}
    bump_version: ${{ inputs.bump_version }}
    secrets: inherit